const generateRScript = (colorBy, legendSettings) => {
  const isItalic = colorBy === 'species' || colorBy === 'subspecies' || colorBy === 'genus' || colorBy === 'scientific_name'

  return `# ════════════════════════════════════════════════════════════════════════════════
# Wings Atlas - R Script for Publication-Quality Export
# Generated by Wings Atlas (https://rapidspeciation.github.io/ithomiini_maps/)
# ════════════════════════════════════════════════════════════════════════════════
#
# This script creates a map matching the web app preview with:
#   - Configurable basemap (via maptiles package)
#   - Styled legend with rounded corners and optional shapes
#   - Scale bar
#   - Point styling with stroke and optional shapes per group
#   - Display name formatting (predefined or custom)
#
# Output: PDF, PNG, and SVG files suitable for publications
# ════════════════════════════════════════════════════════════════════════════════

# ── 1. Install and load packages ──
packages <- c("sf", "ggplot2", "dplyr", "tidyr", "jsonlite", "maptiles", "tidyterra", "ggspatial", "grid", "png", "stringr")
for (pkg in packages) if (!require(pkg, quietly = TRUE, character.only = TRUE)) install.packages(pkg)
invisible(lapply(packages, library, character.only = TRUE))

# ── 2. Load data ──
cat("Loading exported data...\\n")
points <- st_read("data.geojson", quiet = TRUE)
config <- fromJSON("view_config.json")
legend_data <- fromJSON("legend.json")
bounds <- list(xmin = config$bounds$west, xmax = config$bounds$east, ymin = config$bounds$south, ymax = config$bounds$north)
aspect_ratio <- config$aspectRatio
if (is.null(aspect_ratio)) aspect_ratio <- 16 / 9
if (!"species" %in% names(points) && "scientific_name" %in% names(points)) points$species <- points$scientific_name
cat(sprintf("  %d points loaded\\n", nrow(points)))
cat(sprintf("  Bounds: [%.2f, %.2f] to [%.2f, %.2f]\\n", bounds$xmin, bounds$ymin, bounds$xmax, bounds$ymax))
cat(sprintf("  Aspect ratio: %.3f\\n", aspect_ratio))

# ── 3. Load basemap ──
# Available providers (change basemap_provider below):
#   "CartoDB.DarkMatter"       Dark theme (default, matches web app) - retina OK
#   "CartoDB.Positron"         Light theme - retina OK
#   "CartoDB.Voyager"          Colored roads - retina OK
#   "Stadia.AlidadeSmooth"     Smooth light - retina OK
#   "Stadia.AlidadeSmoothDark" Smooth dark - retina OK
#   "OpenStreetMap"            Standard OSM (no retina)
#   "Esri.WorldImagery"        Satellite imagery (no retina)
#   "Esri.WorldTopoMap"        Topographic (no retina)
basemap_provider <- "CartoDB.DarkMatter"
basemap_zoom <- NULL      # NULL = auto-detect, or 1-18 (higher = more detail, slower)
basemap_retina <- TRUE    # TRUE = 2x resolution tiles for CartoDB/Stadia providers
cat(sprintf("\\nLoading basemap (%s, retina=%s)...\\n", basemap_provider, basemap_retina))
buffer <- 0.5
bbox_expanded <- st_bbox(c(xmin = bounds$xmin - buffer, ymin = bounds$ymin - buffer, xmax = bounds$xmax + buffer, ymax = bounds$ymax + buffer), crs = 4326)
basemap <- NULL
tryCatch({
  basemap <- get_tiles(st_as_sfc(bbox_expanded), provider = basemap_provider, zoom = basemap_zoom, crop = TRUE, retina = basemap_retina)
  cat("  Basemap tiles loaded successfully\\n")
  if (basemap_retina) cat("  (High-resolution retina tiles)\\n")
}, error = function(e) {
  cat(sprintf("  Could not fetch tiles: %s\\n", e$message))
  cat("  Falling back to exported basemap.png\\n")
})
basemap_png <- NULL
if (is.null(basemap) && file.exists("basemap.png")) {
  basemap_png <- readPNG("basemap.png")
  cat("  Loaded basemap.png fallback\\n")
}

# ── 4. Prepare legend data ──
legend_max_items <- legend_data$maxItems
if (is.null(legend_max_items)) legend_max_items <- 15
legend_df <- as.data.frame(legend_data$items)
legend_df$order_idx <- seq_len(nrow(legend_df))
cat(sprintf("\\nLegend: %d categories (showing max %d)\\n", nrow(legend_df), legend_max_items))

# ── 5. Display name formatting functions ──
# display_name_format options: "full" (Mechanitis polymnia), "firstLetterGenus" (M. polymnia),
#   "syllableGenus" (Mec. polymnia), "custom" (from legend_data$displayNames)
# prefix_format options: "none" (casabranca), "firstLetterBoth" (M. p. casabranca),
#   "syllableBoth" (Mec. pol. casabranca), "custom" (from legend_data$abbreviations)
get_first_syllable <- function(word) {
  if (is.null(word) || nchar(word) <= 3) return(word)
  vowels <- c("a", "e", "i", "o", "u", "y")
  lower <- tolower(word)
  chars <- strsplit(lower, "")[[1]]
  result <- ""
  found_vowel <- FALSE
  vowel_ended <- FALSE
  for (i in seq_along(chars)) {
    char <- chars[i]
    is_vowel <- char %in% vowels
    if (!found_vowel) {
      result <- paste0(result, char)
      if (is_vowel) found_vowel <- TRUE
    } else if (!vowel_ended) {
      if (is_vowel) {
        result <- paste0(result, char)
      } else {
        vowel_ended <- TRUE
        result <- paste0(result, char)
        if (nchar(result) >= 3) break
      }
    } else {
      if (is_vowel) break
      result <- paste0(result, char)
      if (nchar(result) >= 4) break
    }
  }
  if (nchar(result) < 2) result <- substr(lower, 1, min(3, nchar(lower)))
  paste0(toupper(substr(result, 1, 1)), substr(result, 2, nchar(result)), ".")
}

generate_abbreviations <- function(species_name) {
  if (is.null(species_name) || species_name == "") return(list(full = species_name))
  parts <- strsplit(trimws(species_name), "\\\\s+")[[1]]
  if (length(parts) < 2) return(list(full = species_name, firstLetterGenus = species_name, syllableGenus = species_name))
  genus <- parts[1]
  epithet <- paste(parts[-1], collapse = " ")
  first_epithet <- parts[2]
  genus_first <- paste0(toupper(substr(genus, 1, 1)), ".")
  epithet_first <- paste0(tolower(substr(first_epithet, 1, 1)), ".")
  genus_syll <- get_first_syllable(genus)
  epithet_syll <- tolower(get_first_syllable(first_epithet))
  list(
    full = species_name,
    firstLetterGenus = paste(genus_first, epithet),
    firstLetterBoth = paste(genus_first, epithet_first),
    syllableGenus = paste(genus_syll, epithet),
    syllableBoth = paste(genus_syll, epithet_syll)
  )
}

apply_display_format <- function(species_name, format, custom_names = NULL) {
  if (format == "custom" && !is.null(custom_names) && species_name %in% names(custom_names)) return(custom_names[[species_name]])
  abbrevs <- generate_abbreviations(species_name)
  switch(format, "full" = abbrevs$full, "firstLetterGenus" = abbrevs$firstLetterGenus, "syllableGenus" = abbrevs$syllableGenus, abbrevs$full)
}

apply_prefix_format <- function(species_name, format, custom_abbrevs = NULL) {
  if (format == "none") return("")
  if (format == "custom" && !is.null(custom_abbrevs) && species_name %in% names(custom_abbrevs)) return(custom_abbrevs[[species_name]])
  abbrevs <- generate_abbreviations(species_name)
  switch(format, "firstLetterBoth" = abbrevs$firstLetterBoth, "syllableBoth" = abbrevs$syllableBoth, "none" = "", abbrevs$syllableBoth)
}

# ── 6. Shape utilities ──
# Filled shapes that support fill + border: 21=circle, 22=square, 23=diamond, 24=triangle-up, 25=triangle-down
SHAPES <- c(circle = 21, square = 22, triangle = 24, rhombus = 23)

# ── 7. Legend settings (from export) ──
show_headers <- if (!is.null(legend_data$showHeaders)) legend_data$showHeaders else FALSE
group_by <- if (!is.null(legend_data$groupBy)) legend_data$groupBy else "species"
display_name_format <- if (!is.null(legend_data$displayNameFormat)) legend_data$displayNameFormat else "full"
prefix_format <- if (!is.null(legend_data$prefixFormat)) legend_data$prefixFormat else "syllableBoth"
shapes_enabled <- if (!is.null(legend_data$shapesEnabled)) legend_data$shapesEnabled else FALSE
custom_display_names <- legend_data$displayNames
custom_abbreviations <- legend_data$abbreviations
group_shapes <- legend_data$groupShapes
if (is.null(group_shapes)) group_shapes <- list()
legend_groups <- legend_data$groups
if (is.null(legend_groups)) legend_groups <- list()
use_grouped_legend <- group_by != "none" && length(legend_groups) > 0
legend_pos_x <- if (!is.null(legend_data$position$x)) legend_data$position$x else 0.02
legend_pos_y <- if (!is.null(legend_data$position$y)) legend_data$position$y else 0.92
cat(sprintf("  Display name format: %s\\n", display_name_format))
cat(sprintf("  Prefix format: %s\\n", prefix_format))
cat(sprintf("  Show headers: %s\\n", show_headers))
cat(sprintf("  Group by: %s\\n", group_by))
cat(sprintf("  Shapes enabled: %s\\n", shapes_enabled))

# ── 8. Styling configuration ──
# For light themes, try: bg_color="#f5f5f5", legend_bg="#ffffff", legend_border="#cccccc",
#   legend_title_color="#666666", legend_text_color="#333333", scale_bar_color="#333333"
STYLE <- list(
  bg_color = "#1a1a2e",       # "#f5f5f5" for light themes
  point_size = 2.5,
  point_alpha = 0.85,
  point_stroke_color = "white",
  point_stroke_alpha = 0.3,
  point_stroke_width = 0.5,
  legend_bg = "#252540",
  legend_bg_alpha = 0.95,     # 0 = transparent, 1 = opaque
  legend_border = "#3d3d5c",
  legend_title_color = "#888888",
  legend_text_color = "#e0e0e0",
  legend_font_size = 8,
  legend_title_size = 10,
  legend_width = 0.22,
  legend_padding = 0.015,
  legend_item_height = 0.028,
  scale_bar_color = "#e0e0e0", # "#333333" for light themes
  # DPI affects text/points/vectors but NOT basemap tile resolution.
  # For sharper basemaps, use basemap_retina=TRUE and/or increase basemap_zoom.
  # PDF/SVG are vector formats - only the basemap raster is affected by DPI.
  base_size = 12,  # base dimension in inches (width for landscape, height for portrait)
  dpi = 300        # dots per inch for PNG rasterization
)
if (aspect_ratio >= 1) {
  output_width <- STYLE$base_size
  output_height <- STYLE$base_size / aspect_ratio
} else {
  output_height <- STYLE$base_size
  output_width <- STYLE$base_size * aspect_ratio
}
cat(sprintf("  Output size: %.1f x %.1f inches\\n", output_width, output_height))

# ── 9. Legend grob builders ──
legend_background <- function(x0, y0, w, h, style) {
  roundrectGrob(
    x = x0, y = y0, width = w, height = h,
    just = c("left", "bottom"), r = unit(8, "pt"),
    gp = gpar(fill = alpha(style$legend_bg, style$legend_bg_alpha), col = style$legend_border, lwd = 1)
  )
}

legend_title_grob <- function(title, x0, y0, total_h, padding, style) {
  textGrob(
    toupper(title),
    x = x0 + padding,
    y = y0 + total_h - padding - (style$legend_item_height * 1.8) / 2,
    just = c("left", "center"),
    gp = gpar(col = style$legend_title_color, fontsize = style$legend_title_size, fontface = "bold")
  )
}

legend_dot <- function(x, y, color, shape, use_shapes, style, stroke_color = "white", stroke_alpha = 0.3, size = 0.006) {
  if (use_shapes && !is.null(shape) && shape != "circle") {
    shape_code <- SHAPES[shape]
    if (length(shape_code) == 0 || is.na(shape_code)) shape_code <- 21
    return(pointsGrob(x = x, y = y, pch = as.numeric(shape_code[1]), size = unit(size * 2, "npc"), gp = gpar(fill = color, col = alpha(stroke_color, stroke_alpha), lwd = 0.5)))
  }
  circleGrob(x = x, y = y, r = size, gp = gpar(fill = color, col = alpha(stroke_color, stroke_alpha), lwd = 0.5))
}

legend_more_indicator <- function(count, x0, y0, more_h, style, indent = 0) {
  iy <- y0 + style$legend_padding + more_h / 2
  grobTree(
    circleGrob(
      x = x0 + style$legend_padding + indent + 0.012, y = iy, r = 0.006,
      gp = gpar(fill = "#888888", col = alpha("white", 0.3), lwd = 0.5)
    ),
    textGrob(
      sprintf("+ %d more...", count),
      x = x0 + style$legend_padding + indent + 0.028, y = iy,
      just = c("left", "center"),
      gp = gpar(col = style$legend_title_color, fontsize = style$legend_font_size - 1, fontface = "italic")
    )
  )
}

# Cap items to fit within available vertical space (prevents legend exceeding image)
max_items_for_height <- function(pos_y, style, has_headers = FALSE) {
  available_h <- pos_y - 0.03  # bottom margin
  title_h <- style$legend_item_height * 1.8
  more_h <- style$legend_item_height * 1.2
  usable_h <- available_h - title_h - more_h - style$legend_padding * 3
  if (usable_h <= 0) return(1)
  # Headers use 1.4x item height; estimate ~1 header per 4 items for grouped legends
  effective_h <- if (has_headers) style$legend_item_height * 1.15 else style$legend_item_height
  max(1, floor(usable_h / effective_h))
}

smart_legend_width <- function(labels, style, indent = 0) {
  if (length(labels) == 0) return(0.12)
  lengths <- nchar(labels)
  # Use max length when few items; P90 quantile for very large legends
  target_len <- if (length(labels) <= 30) max(lengths) else as.numeric(stats::quantile(lengths, probs = 0.9, na.rm = TRUE, names = FALSE))
  # Width = left_padding + indent + dot_space + text + right_padding
  label_start <- style$legend_padding + indent + 0.028
  width_guess <- label_start + 0.0065 * max(8, target_len) + 0.02
  # Cap at legend_width only for very large legends (>30 items)
  if (length(labels) <= 30) max(0.12, width_guess) else min(style$legend_width, max(0.12, width_guess))
}

legend_max_chars <- function(legend_w, style, indent = 0) {
  label_x <- style$legend_padding + indent + 0.028
  available_w <- max(0.05, legend_w - label_x - 0.01)
  max(10, floor(available_w / 0.006))
}

truncate_label <- function(label, max_chars) {
  stringr::str_trunc(label, width = max_chars, ellipsis = "...")
}

create_legend <- function(items, title, max_items, italic = FALSE, style = STYLE, pos_x = 0.02, pos_y = 0.92, use_shapes = FALSE) {
  max_items <- min(max_items, max_items_for_height(pos_y, style))
  n_items <- min(nrow(items), max_items)
  has_more <- nrow(items) > max_items
  title_h <- style$legend_item_height * 1.8
  content_h <- n_items * style$legend_item_height
  more_h <- if (has_more) style$legend_item_height * 1.2 else 0
  total_h <- title_h + content_h + more_h + style$legend_padding * 3
  visible_labels <- if (n_items > 0) items$label[seq_len(n_items)] else character(0)
  legend_w <- smart_legend_width(visible_labels, style)
  max_chars <- legend_max_chars(legend_w, style)
  x0 <- pos_x
  y0 <- pos_y - total_h  # pos_y is TOP edge, convert to bottom for grob placement

  grobs <- list(
    bg = legend_background(x0, y0, legend_w, total_h, style),
    title = legend_title_grob(title, x0, y0, total_h, style$legend_padding, style)
  )

  for (i in seq_len(n_items)) {
    item_y <- y0 + total_h - title_h - style$legend_padding - (i - 0.5) * style$legend_item_height
    item_shape <- if (use_shapes && "shape" %in% names(items)) items$shape[i] else "circle"
    grobs[[paste0("dot_", i)]] <- legend_dot(x0 + style$legend_padding + 0.012, item_y, items$color[i], item_shape, use_shapes, style)
    grobs[[paste0("label_", i)]] <- textGrob(
      truncate_label(items$label[i], max_chars),
      x = x0 + style$legend_padding + 0.028,
      y = item_y,
      just = c("left", "center"),
      gp = gpar(col = style$legend_text_color, fontsize = style$legend_font_size, fontface = if (italic) "italic" else "plain")
    )
  }
  if (has_more) grobs$more <- legend_more_indicator(nrow(items) - max_items, x0, y0, more_h, style)
  do.call(grobTree, grobs)
}

create_grouped_legend <- function(items, groups, title, max_items, style = STYLE,
                                  pos_x = 0.02, pos_y = 0.92, use_shapes = FALSE,
                                  show_headers = TRUE, display_names = NULL, group_shapes = NULL) {
  sorted_species <- sort(names(groups))
  total_items <- nrow(items)
  items_shown <- 0
  headers_shown <- 0
  truncated <- FALSE

  title_h <- style$legend_item_height * 1.8
  header_h <- if (show_headers) style$legend_item_height * 1.4 else 0
  item_h <- style$legend_item_height
  more_h <- style$legend_item_height * 1.2
  max_legend_h <- pos_y - 0.03  # leave bottom margin
  base_h <- title_h + more_h + style$legend_padding * 3
  current_h <- base_h

  for (sp in sorted_species) {
    subspecies_list <- groups[[sp]]
    if (items_shown >= max_items) { truncated <- TRUE; break }
    # Check if header fits
    if (show_headers && current_h + header_h > max_legend_h) { truncated <- TRUE; break }
    if (show_headers) { current_h <- current_h + header_h; headers_shown <- headers_shown + 1 }
    # Fit as many subspecies as possible
    for (j in seq_along(subspecies_list)) {
      if (items_shown >= max_items || current_h + item_h > max_legend_h) { truncated <- TRUE; break }
      current_h <- current_h + item_h
      items_shown <- items_shown + 1
    }
    if (truncated) break
  }

  if (!truncated) more_h <- 0  # no "more" indicator needed if all items shown
  content_h <- if (show_headers) headers_shown * header_h + items_shown * item_h else items_shown * item_h
  total_h <- title_h + content_h + more_h + style$legend_padding * 3
  header_labels <- if (show_headers && !is.null(display_names)) unlist(display_names) else character(0)
  indent <- if (show_headers) 0.016 else 0
  legend_w <- smart_legend_width(c(items$label, header_labels), style, indent)
  max_item_chars <- legend_max_chars(legend_w, style, if (show_headers) 0.016 else 0)
  max_header_chars <- legend_max_chars(legend_w, style, if (use_shapes) 0.024 else 0)
  x0 <- pos_x
  y0 <- pos_y - total_h  # pos_y is TOP edge, convert to bottom for grob placement

  grobs <- list(
    bg = legend_background(x0, y0, legend_w, total_h, style),
    title = legend_title_grob(title, x0, y0, total_h, style$legend_padding, style)
  )

  current_y <- y0 + total_h - title_h - style$legend_padding
  item_idx <- 1
  grob_idx <- 1

  for (sp in sorted_species) {
    subspecies_list <- groups[[sp]]
    if (item_idx > items_shown) break
    sp_display <- if (!is.null(display_names) && sp %in% names(display_names)) display_names[[sp]] else sp
    sp_shape <- if (!is.null(group_shapes) && sp %in% names(group_shapes)) group_shapes[[sp]] else "circle"

    if (show_headers) {
      current_y <- current_y - header_h / 2
      if (use_shapes && sp_shape != "circle") {
        grobs[[paste0("header_shape_", grob_idx)]] <- legend_dot(
          x0 + style$legend_padding + 0.010, current_y, "transparent", sp_shape, TRUE, style,
          stroke_color = style$legend_text_color, stroke_alpha = 0.6, size = 0.005
        )
      }
      header_x <- if (use_shapes) x0 + style$legend_padding + 0.024 else x0 + style$legend_padding
      grobs[[paste0("header_", grob_idx)]] <- textGrob(
        truncate_label(sp_display, max_header_chars),
        x = header_x,
        y = current_y,
        just = c("left", "center"),
        gp = gpar(col = style$legend_text_color, fontsize = style$legend_font_size, fontface = "bold.italic")
      )
      current_y <- current_y - header_h / 2
      grob_idx <- grob_idx + 1
    }

    for (subsp in subspecies_list) {
      if (item_idx > nrow(items)) break
      item_row <- which(items$label == subsp | grepl(paste0(subsp, "$"), items$label))[1]
      if (is.na(item_row)) next
      current_y <- current_y - item_h / 2
      indent <- if (show_headers) 0.016 else 0
      grobs[[paste0("dot_", grob_idx)]] <- legend_dot(
        x0 + style$legend_padding + indent + 0.012, current_y,
        items$color[item_row], "circle", FALSE, style
      )
      grobs[[paste0("label_", grob_idx)]] <- textGrob(
        truncate_label(items$label[item_row], max_item_chars),
        x = x0 + style$legend_padding + indent + 0.028,
        y = current_y,
        just = c("left", "center"),
        gp = gpar(col = style$legend_text_color, fontsize = style$legend_font_size, fontface = "italic")
      )
      current_y <- current_y - item_h / 2
      item_idx <- item_idx + 1
      grob_idx <- grob_idx + 1
      if (item_idx > items_shown) break
    }
    if (item_idx > items_shown) break
  }

  if (truncated) grobs$more <- legend_more_indicator(total_items - items_shown, x0, y0, more_h, style)
  do.call(grobTree, grobs)
}

# ── 10. Apply prefix format to legend labels ──
cat("\\nFormatting legend labels...\\n")
cat(sprintf("  Prefix format: %s\\n", prefix_format))
if (prefix_format != "none" && "species" %in% names(legend_df)) {
  legend_df$display_label <- sapply(seq_len(nrow(legend_df)), function(i) {
    subspecies_name <- legend_df$label[i]
    species_name <- legend_df$species[i]
    prefix <- apply_prefix_format(species_name, prefix_format, custom_abbreviations)
    if (prefix == "" || is.null(prefix)) subspecies_name else paste(prefix, subspecies_name)
  })
} else {
  legend_df$display_label <- legend_df$label
}
legend_df$label <- legend_df$display_label

# ── 11. Prepare point + legend shapes ──
if (shapes_enabled) {
  cat("\\nApplying shapes to data points...\\n")
  if (length(group_shapes) > 0) {
    cat("  Group shapes mapping:\\n")
    for (sp_name in names(group_shapes)) cat(sprintf("    %s -> %s\\n", sp_name, group_shapes[[sp_name]]))
  } else {
    cat("  No custom shapes defined (all circles)\\n")
  }

  shape_column <- if ("scientific_name" %in% names(points)) "scientific_name" else "species"
  cat(sprintf("  Using column '%s' for shape mapping\\n", shape_column))
  points$shape_code <- sapply(points[[shape_column]], function(sp) {
    shape_name <- group_shapes[[sp]]
    if (is.null(shape_name)) shape_name <- "circle"
    shape_code <- SHAPES[shape_name]
    if (length(shape_code) == 0 || is.na(shape_code)) 21 else as.numeric(shape_code[1])
  })

  if ("species" %in% names(legend_df)) {
    legend_df$shape <- sapply(legend_df$species, function(sp) {
      shape_name <- group_shapes[[sp]]
      if (is.null(shape_name)) "circle" else shape_name
    })
  } else {
    legend_df$shape <- "circle"
  }
  cat(sprintf("  Shapes assigned: %d unique shapes\\n", length(unique(points$shape_code))))
  cat(sprintf("  Shape codes in data: %s\\n", paste(unique(points$shape_code), collapse = ", ")))
} else {
  points$shape_code <- 21
  legend_df$shape <- "circle"
}

# ── 12. Build the map ──
cat("\\nCreating map...\\n")
p <- ggplot()
if (!is.null(basemap)) {
  p <- p + geom_spatraster_rgb(data = basemap)
} else if (!is.null(basemap_png)) {
  p <- p + annotation_raster(basemap_png, xmin = bounds$xmin, xmax = bounds$xmax, ymin = bounds$ymin, ymax = bounds$ymax)
}

if (file.exists("range_polygons.geojson")) {
  cat("  Loading range polygons...\\n")
  range_polys <- st_read("range_polygons.geojson", quiet = TRUE)
  if (nrow(range_polys) > 0) {
    p <- p +
      geom_sf(
        data = range_polys,
        aes(fill = color),
        color = NA,
        alpha = 0.3
      ) +
      geom_sf(
        data = range_polys,
        fill = NA,
        aes(color = color),
        linewidth = 0.4,
        alpha = 0.6
      ) +
      scale_color_identity()
    cat(sprintf("  %d range polygons added\\n", nrow(range_polys)))
  }
}

if (shapes_enabled && "shape_code" %in% names(points)) {
  p <- p +
    geom_sf(
      data = points,
      aes(fill = display_color, shape = factor(shape_code)),
      color = alpha(STYLE$point_stroke_color, STYLE$point_stroke_alpha),
      size = STYLE$point_size,
      alpha = STYLE$point_alpha,
      stroke = STYLE$point_stroke_width
    ) +
    scale_fill_identity() +
    scale_shape_manual(values = c("21" = 21, "22" = 22, "23" = 23, "24" = 24, "25" = 25), guide = "none")
} else {
  p <- p +
    geom_sf(
      data = points,
      aes(fill = display_color),
      color = alpha(STYLE$point_stroke_color, STYLE$point_stroke_alpha),
      size = STYLE$point_size,
      alpha = STYLE$point_alpha,
      stroke = STYLE$point_stroke_width,
      shape = 21
    ) +
    scale_fill_identity()
}

p <- p +
  coord_sf(xlim = c(bounds$xmin, bounds$xmax), ylim = c(bounds$ymin, bounds$ymax), expand = FALSE) +
  annotation_scale(
    location = "br",
    width_hint = 0.15,
    style = "ticks",
    text_col = STYLE$scale_bar_color,
    line_col = STYLE$scale_bar_color,
    pad_x = unit(0.5, "cm"),
    pad_y = unit(0.5, "cm")
  ) +
  theme_void() +
  theme(plot.background = element_rect(fill = STYLE$bg_color, color = NA), panel.background = element_rect(fill = STYLE$bg_color, color = NA))

if (use_grouped_legend) {
  cat("  Using grouped legend (grouped by species)\\n")
  legend_grob <- create_grouped_legend(
    legend_df,
    legend_groups,
    legend_data$title,
    legend_max_items,
    style = STYLE,
    pos_x = legend_pos_x,
    pos_y = legend_pos_y,
    use_shapes = shapes_enabled,
    show_headers = show_headers,
    display_names = custom_display_names,
    group_shapes = group_shapes
  )
} else {
  cat("  Using flat legend (no grouping)\\n")
  legend_grob <- create_legend(
    legend_df,
    legend_data$title,
    legend_max_items,
    ${isItalic ? 'TRUE' : 'FALSE'},
    style = STYLE,
    pos_x = legend_pos_x,
    pos_y = legend_pos_y,
    use_shapes = shapes_enabled
  )
}

p_final <- p + annotation_custom(legend_grob, xmin = -Inf, xmax = Inf, ymin = -Inf, ymax = Inf)

# ── 13. Save outputs ──
cat("\\nSaving outputs...\\n")
print(p_final)
ggsave("ithomiini_map.pdf", plot = p_final, width = output_width, height = output_height, dpi = STYLE$dpi)
cat("  ithomiini_map.pdf\\n")
ggsave("ithomiini_map.png", plot = p_final, width = output_width, height = output_height, dpi = STYLE$dpi)
cat("  ithomiini_map.png\\n")
tryCatch({
  ggsave("ithomiini_map.svg", plot = p_final, width = output_width, height = output_height, dpi = STYLE$dpi)
  cat("  ithomiini_map.svg\\n")
}, error = function(e) {
  cat(sprintf("  SVG export skipped: %s\\n", e$message))
  cat("  Install 'svglite' to enable SVG export: install.packages(\\"svglite\\")\\n")
})

cat("\\nExport complete!\\n")
cat("Output files:\\n")
cat("  ithomiini_map.pdf - Vector PDF for publications\\n")
cat("  ithomiini_map.png - High-resolution raster (300 DPI)\\n")
cat("  ithomiini_map.svg - Editable vector (if svglite is available)\\n")
cat("Tip: edit STYLE, basemap_provider, basemap_zoom, basemap_retina above.\\n")
`
}

export { generateRScript }
